apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    - name: cloud-provider
      value: "external"
timeouts:
  controlPlaneComponentHealthCheck: "4m0s"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.33.0
clusterName: kubernetes
certificatesDir: /etc/kubernetes/pki
imageRepository: registry.k8s.io
apiServer:
  certSANs:
  - localhost
  extraArgs:
    - name: authorization-mode
      value: Node,RBAC
controllerManager:
  extraArgs:
    - name: cloud-provider
      value: "external"
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
