apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-pd
provisioner: pd.csi.storage.gke.io # kubernetes.io/gce-pd
parameters:
  type: pd-standard  # or pd-ssd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
